name: Ruby CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.1"
          bundler-cache: true
      
      - name: Install dependencies
        run: bundle install
          
      - name: Run tests
        run: ruby tests/test_helper.rb
          
      - name: Run style checks
        run: |
          gem install rubocop
          rubocop

      - name: Coverage report
        run: |
          gem install simplecov
          COVERAGE=true ruby -I. tests/**/*_test.rb